name: React-weather-app

on:
  push:
    branches: [dev]

permissions:
  id-token: write # Required for OIDC
  contents: read # To fetch the repository code

env:
  DOCKER_REPO: "nunuokorie/dgcl-project"

jobs:
  build:
    name: Build and deploy react-weather-app
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::621214085626:role/GitHub-to-ECR-and-ECS

      - name: Confirm OIDC
        run: aws sts get-caller-identity

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: add nodejs environment
        uses: actions/setup-node@v3.9.1

      - name: install nodejs dependencies
        run: npm install

      ##- name: run unit test
      ##  run: npm test

      - name: optimize static website
        run: npm run build

      - name: deploy to s3
        run: aws s3 sync build/ s3://remote-backend300525

      - name: docker hub login with credentials
        uses: docker/login-action@v3.4.0
        with:
          username: nunuokorie
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: docker build and push
        run: |
          docker build -t $DOCKER_REPO:$GITHUB_RUN_NUMBER .         
          docker push $DOCKER_REPO:$GITHUB_RUN_NUMBER

      - name: ssh to instance
        run: |
          mkdir -p ~/.ssh 
          echo "${{secrets.PROD_EC2_KEY}}" > ~/.ssh/id_rsa 
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan 54.226.12.148 >> ~/.ssh/known_hosts 
          ssh -i ~/.ssh/id_rsa ubuntu@54.226.12.148 <<EOF 
          uptime && hostname
          docker stop $DOCKER_REPO:$GITHUB_RUN_NUMBER || true
          docker rm $DOCKER_REPO:$GITHUB_RUN_NUMBER || true
          docker pull $DOCKER_REPO:$GITHUB_RUN_NUMBER
          docker run $DOCKER_REPO:$GITHUB_RUN_NUMBER
          EOF
