name: React-weather-app

on:
  push:
    branches: [dev]

permissions:
  id-token: write   # Required for OIDC
  contents: read    # To fetch the repository code

jobs:
  build:
    name: Build and deploy react-weather-app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::621214085626:role/GitHub-to-ECR-and-ECS

      - name: Confirm OIDC
        run: aws sts get-caller-identity

      - name: add nodejs environment
        uses: actions/setup-node@v3.9.1

      - name: install nodejs dependencies
        run: npm install       

      - name: optimize static website
        run: npm run build

      - name: deploy to s3
        run: aws s3 sync build/ s3://remote-backend300525 --delete
        

      

